export const SignUpData="SignUpData"
export const logInData="logInData"
export const GETCOURSE="GETCOURSE"
export const POSTCOURSE="POSTCOURSE"
export const STUDENTCOURSE="STUDENTCOURSE"
export const GETSTUDENTCOURSE="GETSTUDENTCOURSE"
export const GETSCHEDULE="GETSCHEDULE"
export const SCHEDULE="SCHEDULE"